server:
  port: 8080

spring:
  application:
    name: sample-bank-app

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: sample-bank-app

logging:
  level:
    root: INFO

observability:

  environment: ${OBSERVABILITY_ENVIRONMENT:DEV}

  bank:
    code: ${OBSERVABILITY_BANK_CODE:NPST}
    name: Bharat Bank
    region: IN

  sink:
    endpoint: ${OBSERVABILITY_LOGGING_ENDPOINT:http://localhost:8090/api/v1/logs}
    audit-endpoint: ${OBSERVABILITY_AUDIT_ENDPOINT:http://localhost:8090/api/v1/audit}

mock:

  cbs:
    base-url: ${MOCK_CBS_BASE_URL:http://localhost:8080/mock-cbs}
    timeout: 3s

  statement:
    max-days: 365

  transfer:
    limit: 200000.00

  beneficiary:
    cooling-off: PT30M
